In [ ]:
'''
SESSIONS 2,  3, 4 
Reading imaegs
Saving images
Showing images
Channels
numpy arrays
Padding
Video (webcam)
Drawing shapes (line, circle, rectangle)
Text
'''

In [5]:
import cv2
import numpy as np

In [6]:
np.zeros((6,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Channels are 3 : means RGB(0,1,2)

In [7]:
image = cv2.imread("Pic.jpeg")
print(image)

[[[18 42 48]
  [19 43 49]
  [20 43 51]
  ...
  [ 5 17 27]
  [ 5 15 25]
  [ 5 15 25]]

 [[18 42 48]
  [18 42 48]
  [20 43 51]
  ...
  [ 7 19 29]
  [ 6 18 28]
  [ 7 17 27]]

 [[17 41 47]
  [18 42 48]
  [19 42 50]
  ...
  [ 9 21 31]
  [ 8 20 30]
  [ 7 19 29]]

 ...

 [[10 19 32]
  [10 19 32]
  [10 19 32]
  ...
  [ 8 27 35]
  [ 8 27 35]
  [ 8 27 35]]

 [[ 8 17 30]
  [ 8 17 30]
  [ 8 17 30]
  ...
  [ 7 26 34]
  [ 7 26 34]
  [ 7 26 34]]

 [[11 20 33]
  [10 19 32]
  [10 19 32]
  ...
  [ 7 26 34]
  [ 7 26 34]
  [ 7 26 34]]]


In [ ]:
cv2.imshow("man",image)
cv2.waitKey(0)

2025-01-13 16:08:00.177 Python[48378:2261469] +[IMKClient subclass]: chose IMKClient_Legacy
2025-01-13 16:08:00.177 Python[48378:2261469] +[IMKInputSession subclass]: chose IMKInputSession_Legacy


In [8]:
image.shape  # h, w , c dimensions:  rows, columns, channels 

(576, 576, 3)

In [9]:
image.shape # shape of the image          

(576, 576, 3)

In [10]:
green_image = image[:,:,1] # all rows, all columns, and only first channel

In [13]:
green_image # there is no more third attribute for channels because it filtered in last cell

array([[42, 43, 43, ..., 17, 15, 15],
       [42, 42, 43, ..., 19, 18, 17],
       [41, 42, 42, ..., 21, 20, 19],
       ...,
       [19, 19, 19, ..., 27, 27, 27],
       [17, 17, 17, ..., 26, 26, 26],
       [20, 19, 19, ..., 26, 26, 26]], shape=(576, 576), dtype=uint8)

In [ ]:
# SHOWING IMAGES
cv2.imshow('green_image',green_image) # it should show the image in green but it shows in black & white (no matter which channel we chose it always  
# be black and white
cv2.waitKey(300)

2025-01-13 16:46:13.925 Python[48763:2282109] +[IMKClient subclass]: chose IMKClient_Legacy
2025-01-13 16:46:13.925 Python[48763:2282109] +[IMKInputSession subclass]: chose IMKInputSession_Legacy


SystemError: <built-in function destroyAllWindows> returned NULL without setting an exception

In [15]:
# SAVING IMAGES
cv2.imwrite("popo.jpg",green_image)

True

In [17]:
# cv2.destroyWindow()
cv2.destroyAllWindows()  # destroy all windows to not allocate memory


In [22]:
#Slicing
# assign to all of the channels to be black
print(image.shape)
image[10:500, 100:550, :] = 0

(576, 576, 3)


NOTE: everything follows RGB but CV library follows BGR 
